version: '3.8'

services:
    bot:
        build: .
        container_name: bot
        restart: unless-stopped
        links:
            - player
        env_file:
            - .env
        environment:
            - LAVALINK_NODES=lavalink://1:password@player:2333 lavalink://2:password@player2:2333
    player:
        build: ghcr.io/lavalink-devs/lavalink:v4-update-lp
        container_name: player
        restart: unless-stopped
        volumes:
            # Mount application.yml for configuration (optional, see Lavalink documentation)
            - ./lavalink/application.yml:/opt/Lavalink/application.yml
        ports:
            # Expose port for your application to connect (optional if container network is used)
            - '2333:2333'
    player2:
        build: ghcr.io/lavalink-devs/lavalink:v4-update-lp
        container_name: player2
        restart: unless-stopped
        volumes:
            # Mount application.yml for configuration (optional, see Lavalink documentation)
            - ./lavalink/application.yml:/opt/Lavalink/application.yml
