version: "3.8"

services:
  backend:
    links:
      - player
    depends_on:
      - player
    build: .
    restart: always
  player:
    # pin the image version to Lavalink v4
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: player
    restart: unless-stopped
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx6G
      # set lavalink server port
      - SERVER_PORT=2333
      - SERVER_ADDRESS=0.0.0.0
      # set password for lavalink
      - LAVALINK_SERVER_PASSWORD=password
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "2333:2333"
