name: Build and Run Image

on:
    push:
        branches: [master, dev]

jobs:
    build-and-run:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Build Docker image
              run: make build
            - name: Make env
              run: make env
            - name: docker compose down
              run: make down
            - name: docker compose up
              run: make up
