name: Build Player

on:
  push:
    tags:
      - "player"

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            apps/player
          sparse-checkout-cone-mode: false

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push player
        uses: docker/build-push-action@v6
        with:
          context: apps/player
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/remove158/player
          push: true
          build-args: |
            POT_TOKEN=${{ secrets.POT_TOKEN }}
            VISITOR_DATA=${{ secrets.VISITOR_DATA }}
            LAVA_LINK_PASSWORD=${{ secrets.LAVA_LINK_PASSWORD }}
